# Generated by Django 2.1 on 2018-11-11 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lost', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lost',
            name='description',
        ),
        migrations.AddField(
            model_name='lost',
            name='brand',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='lost',
            name='color',
            field=models.TextField(blank=True),
        ),
    ]
