# Generated by Django 2.1 on 2018-11-05 20:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lost', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='lost',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='lost.Lost'),
        ),
    ]
