# Generated by Django 2.1 on 2018-11-09 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lost', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lost',
            name='found_status',
            field=models.CharField(default='NF', max_length=2),
        ),
    ]
