# Generated by Django 2.1 on 2018-11-08 06:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('lost', '0002_auto_20181105_2009'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lost',
            old_name='date',
            new_name='date_item_registered',
        ),
        migrations.AddField(
            model_name='lost',
            name='date_item_lost',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
