# Generated by Django 2.1 on 2018-11-08 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lost', '0003_auto_20181108_0602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lost',
            name='date_item_lost',
            field=models.DateTimeField(),
        ),
    ]
