# Generated by Django 2.1 on 2018-11-08 07:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('lost', '0004_auto_20181108_0700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lost',
            name='date_item_lost',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
