# Generated by Django 2.1 on 2018-12-01 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='contact',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
