# Generated by Django 2.1 on 2018-12-02 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='addressline2',
            field=models.TextField(blank=True, null=True),
        ),
    ]
