# Generated by Django 2.1 on 2018-11-09 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('found', '0002_auto_20181109_1526'),
    ]

    operations = [
        migrations.AddField(
            model_name='found',
            name='claimed',
            field=models.CharField(default='NC', max_length=2),
        ),
    ]
